import { useEffect, useState } from 'react'
import { FolderKanban, Plus, Layers3 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { api } from '../utils/api'
import { useResources } from '../context/ResourcesContext'
import Card from '../components/ui/Card'
import Button from '../components/ui/Button'
import Badge from '../components/ui/Badge'

export default function Categories(){
 const {facets,resources}=useResources(); const nav=useNavigate(); const [collections,setCollections]=useState([]); const [clusters,setClusters]=useState([]); const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [category,setCategory]=useState(''); const [message,setMessage]=useState('')
 const load=()=>Promise.all([api.get('/intelligence/collections'),api.get('/intelligence/clusters')]).then(([c,cl])=>{setCollections(c.items||[]);setClusters(cl.items||[])}); useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
 const create=async()=>{if(!name||!category)return;setMessage('');try{await api.post('/intelligence/collections/smart',{name,rule:{category}});setName('');setOpen(false);await load();setMessage('Collection created.')}catch(e){setMessage(e.message)}}
 const categoryCounts=resources.reduce((a,r)=>{a[r.category]=(a[r.category]||0)+1;return a},{})
 return <div className="space-y-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[13px] text-text-muted">Organize by meaning</p><h2 className="mt-1 font-display text-2xl font-semibold text-text">Categories & Collections</h2><p className="mt-1.5 text-[13.5px] text-text-muted">Derived from your real library data.</p></div><Button onClick={()=>setOpen(v=>!v)}><Plus size={15}/>Smart collection</Button></div>{open&&<Card className="p-5"><h3 className="text-sm font-medium text-text">Create smart collection</h3><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Collection name" className="h-10 flex-1 rounded-lg border border-hairline-strong bg-elevated px-3 text-sm text-text"/><select value={category} onChange={e=>setCategory(e.target.value)} className="h-10 rounded-lg border border-hairline-strong bg-elevated px-3 text-sm text-text"><option value="">Choose category</option>{(facets.categories||[]).map(c=><option key={c}>{c}</option>)}</select><Button onClick={create}>Create</Button></div>{message&&<p className="mt-3 text-xs text-text-muted">{message}</p>}</Card>}
 <section><div className="mb-3 flex items-center gap-2"><FolderKanban size={15} className="text-accent-soft"/><h3 className="text-sm font-medium text-text">Categories</h3></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{(facets.categories||[]).map(c=><button key={c} onClick={()=>nav(`/library?category=${encodeURIComponent(c)}`)} className="text-left"><Card className="p-4 h-full hover:border-accent/40 transition-colors"><div className="flex items-center justify-between"><p className="text-sm font-medium text-text">{c}</p><Badge tone="neutral">{categoryCounts[c]||0}</Badge></div><p className="mt-2 text-xs text-text-faint">Open filtered library</p></Card></button>)}</div></section>
 <section><div className="mb-3 flex items-center gap-2"><Layers3 size={15} className="text-accent-soft"/><h3 className="text-sm font-medium text-text">Smart collections</h3></div>{collections.length?<div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{collections.map(c=><button key={c.id} onClick={()=>nav(`/library?collection=${c.id}`)} className="text-left"><Card className="p-4 hover:border-accent/40"><div className="flex justify-between gap-3"><p className="text-sm font-medium text-text">{c.name}</p><span className="text-xs text-text-faint">{c.count}</span></div><p className="mt-2 text-xs text-text-faint">Smart · updates from rule matches</p></Card></button>)}</div>:<Card className="p-6 text-center text-xs text-text-faint">No smart collections yet.</Card>}</section>
 <section><div className="mb-3 flex items-center gap-2"><Layers3 size={15} className="text-accent-soft"/><h3 className="text-sm font-medium text-text">Knowledge clusters</h3></div><div className="flex flex-wrap gap-2">{clusters.map(c=><Badge key={c.cluster} tone="neutral">{c.cluster} · {c.count}</Badge>)}</div></section></div>
}
