import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, Link2Off, RefreshCw, Sparkles, Copy, Layers3, Route } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../utils/api'
import { useResources } from '../context/ResourcesContext'
import Card from '../components/ui/Card'
import Button from '../components/ui/Button'
import Badge from '../components/ui/Badge'
import ErrorState from '../components/ui/ErrorState'

function Metric({icon:Icon,label,value,tone='normal'}){return <Card className="p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-text-muted"><Icon size={15}/>{label}</span><span className={`text-xl font-semibold tabular-nums ${tone==='danger'?'text-danger':tone==='warning'?'text-warning':tone==='success'?'text-success':'text-text'}`}>{value}</span></div></Card>}
export default function LibraryHealth(){
 const {health,refresh}=useResources(); const [dupes,setDupes]=useState([]); const [clusters,setClusters]=useState([]); const [checking,setChecking]=useState(false); const [linkResult,setLinkResult]=useState(null); const [error,setError]=useState(''); const [collections,setCollections]=useState([]); const [topic,setTopic]=useState(''); const [days,setDays]=useState(7); const [roadmap,setRoadmap]=useState(null); const nav=useNavigate()
 const load=async()=>{setError('');try{const [d,c,col]=await Promise.all([api.get('/intelligence/duplicates?limit=20'),api.get('/intelligence/clusters'),api.get('/intelligence/collections')]);setDupes(d.items||[]);setClusters(c.items||[]);setCollections(col.items||[])}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[])
 const checkLinks=async()=>{setChecking(true);setLinkResult(null);try{setLinkResult(await api.post('/intelligence/links/check',{limit:25}));await refresh()}catch(e){setError(e.message)}finally{setChecking(false)}}
 const makeRoadmap=async()=>{if(!topic.trim())return;try{setRoadmap(await api.post('/intelligence/study-plan',{topic,study_days:Number(days)}))}catch(e){setError(e.message)}}
 if(error&&!health)return <ErrorState description={error}/>
 return <div className="space-y-7">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[13px] text-text-muted">Diagnostics + intelligence</p><h2 className="mt-1 font-display text-2xl font-semibold text-text">Library Health</h2><p className="mt-1.5 text-[13.5px] text-text-muted">Real metrics from your SQLite library. Nothing here is mocked.</p></div><Button variant="secondary" onClick={refresh}><RefreshCw size={14}/>Refresh</Button></div>
  <Card className="p-5"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="relative flex h-24 w-24 shrink-0 items-center justify-center rounded-full border-8 border-accent-dim"><span className="text-2xl font-semibold text-text">{health?.health_score ?? 0}%</span></div><div className="min-w-0"><p className="text-sm font-medium text-text">Overall library health</p><p className="mt-1 text-xs leading-relaxed text-text-muted">Calculated from reconciliation, review items, duplicates, AI failures/missing metadata, and verified broken links. Access-restricted or unverified links are not treated as dead.</p><div className="mt-3 flex flex-wrap gap-2"><Badge tone={health?.reconciled?'success':'danger'}>{health?.reconciled?'Import reconciled':'Reconciliation issue'}</Badge><Badge tone="neutral">{health?.total_resources||0} resources</Badge></div></div></div></Card>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={CheckCircle2} label="Saved" value={health?.importable||0} tone="success"/><Metric icon={AlertTriangle} label="Needs review" value={health?.needs_review||0} tone="warning"/><Metric icon={Copy} label="Exact duplicates" value={health?.exact_duplicates||0}/><Metric icon={Link2Off} label="404 links" value={health?.broken_links||0} tone="danger"/></div>
  <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
   <Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-medium text-text">Link verification</h3><p className="mt-1 text-xs text-text-muted">Check up to 25 unverified URLs per run.</p></div><Button size="sm" onClick={checkLinks} disabled={checking}>{checking?<><RefreshCw size={13} className="animate-spin"/>Checking</>:<><Link2Off size={13}/>Check links</>}</Button></div><div className="mt-5 grid grid-cols-3 gap-3 text-xs"><div><p className="text-text-faint">Checked</p><p className="mt-1 text-lg font-medium text-text">{health?.links_checked||0}</p></div><div><p className="text-text-faint">Unverified</p><p className="mt-1 text-lg font-medium text-warning">{health?.unverified_links||0}</p></div><div><p className="text-text-faint">Restricted</p><p className="mt-1 text-lg font-medium text-text">{health?.inaccessible_links||0}</p></div></div>{linkResult&&<p className="mt-4 text-xs text-success">Checked {linkResult.checked} URLs.</p>}</Card>
   <Card className="p-5"><div className="flex items-center gap-2"><Sparkles size={15} className="text-accent-soft"/><h3 className="text-sm font-medium text-text">AI coverage</h3></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-elevated"><div className="h-full rounded-full bg-accent transition-all duration-700" style={{width:`${health?.total_resources?Math.round((health.ai_complete/health.total_resources)*100):0}%`}}/></div><div className="mt-3 flex justify-between text-xs text-text-muted"><span>{health?.ai_complete||0} complete</span><span>{health?.ai_pending||0} pending · {health?.ai_failed||0} failed</span></div></Card>
  </div>
  <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
   <Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-medium text-text">Duplicate candidates</h3><p className="mt-1 text-xs text-text-muted">Deterministic URL/content-ID matches.</p></div><Badge tone="warning">{dupes.length}</Badge></div><div className="mt-4 space-y-2 max-h-72 overflow-auto">{dupes.length?dupes.map(d=><button key={`${d.first_id}-${d.second_id}`} onClick={()=>nav(`/resource/${d.first_id}`)} className="w-full rounded-lg border border-hairline p-3 text-left hover:bg-elevated"><p className="truncate text-xs font-medium text-text">{d.first_title||d.first_url}</p><p className="mt-1 truncate text-[11px] text-text-faint">↔ {d.second_title||d.second_url}</p><span className="mt-2 inline-flex"><Badge tone="neutral">{d.match_type==='CONTENT_ID'?'Same content ID':'Same normalized URL'}</Badge></span></button>):<p className="py-6 text-center text-xs text-text-faint">No duplicate candidates found.</p>}</div></Card>
   <Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-medium text-text">Knowledge clusters</h3><p className="mt-1 text-xs text-text-muted">Groups derived from AI category/subcategory/platform.</p></div><Layers3 size={15} className="text-accent-soft"/></div><div className="mt-4 grid grid-cols-2 gap-2">{clusters.slice(0,10).map(c=><button key={c.cluster} onClick={()=>nav(`/library?category=${encodeURIComponent(c.cluster)}`)} className="rounded-lg bg-elevated p-3 text-left hover:bg-accent-dim"><p className="truncate text-xs font-medium text-text">{c.cluster}</p><p className="mt-1 text-[11px] text-text-faint">{c.count} resources</p></button>)}</div></Card>
  </div>
  <Card className="p-5"><div className="flex items-center gap-2"><Route size={15} className="text-accent-soft"/><div><h3 className="text-sm font-medium text-text">Build a study plan from your library</h3><p className="mt-1 text-xs text-text-muted">Only matched saved resources are used; missing knowledge stays visible instead of being invented.</p></div></div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Next.js authentication" className="h-10 flex-1 rounded-lg border border-hairline-strong bg-elevated px-3 text-sm text-text outline-none focus:border-accent"/><select value={days} onChange={e=>setDays(e.target.value)} className="h-10 rounded-lg border border-hairline-strong bg-elevated px-3 text-sm text-text"><option value="3">3 days</option><option value="7">7 days</option><option value="14">14 days</option></select><Button onClick={makeRoadmap}>Generate</Button></div>{roadmap&&<div className="mt-5 grid gap-2 md:grid-cols-2 lg:grid-cols-3">{roadmap.days.map(day=><div key={day.day} className="rounded-xl border border-hairline p-4"><p className="text-xs font-medium text-accent-soft">Day {day.day}</p><p className="mt-1 text-xs text-text-muted">{day.resources.length} matched resources</p><div className="mt-3 space-y-2">{day.resources.map(r=><Link key={r.id} to={`/resource/${r.id}`} className="block truncate text-xs text-text hover:text-accent-soft">{r.title||r.original_url}</Link>)}</div></div>)}</div>}</Card>
  {collections.length>0&&<Card className="p-5"><h3 className="text-sm font-medium text-text">Smart collections</h3><div className="mt-4 flex flex-wrap gap-2">{collections.map(c=><Badge key={c.id} tone="neutral">{c.name} · {c.count}</Badge>)}</div></Card>}
 </div>
}
