import { useEffect, useState } from 'react'
import { useNavigate, useParams, Link } from 'react-router-dom'
import { ArrowLeft, ExternalLink, Star, Sparkles, Link2, CheckCircle2, AlertCircle } from 'lucide-react'
import { api } from '../utils/api'
import { useResources } from '../context/ResourcesContext'
import Card from '../components/ui/Card'
import Badge from '../components/ui/Badge'
import Button from '../components/ui/Button'
import ErrorState from '../components/ui/ErrorState'
import { platformMeta } from '../utils/platforms'

export default function ResourceDetail(){
 const {id}=useParams(); const nav=useNavigate(); const {toggleFavorite}=useResources(); const [resource,setResource]=useState(null); const [related,setRelated]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 useEffect(()=>{let active=true;setLoading(true);Promise.all([api.get(`/resources/${encodeURIComponent(id)}`),api.get(`/intelligence/resources/${encodeURIComponent(id)}/related?limit=6`)]).then(([r,rel])=>{if(active){setResource(r);setRelated(rel.items||[])}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[id])
 if(loading)return <div className="py-20 text-center text-sm text-text-muted">Loading resource…</div>
 if(error)return <ErrorState onRetry={()=>window.location.reload()} description={error}/>
 if(!resource)return <ErrorState description="Resource not found."/>
 const meta=platformMeta(resource.platform); const Icon=meta.icon
 const tags=resource.ai_tags||[]
 return <div className="space-y-6 max-w-5xl">
  <button onClick={()=>nav(-1)} className="flex items-center gap-2 text-xs text-text-muted hover:text-text"><ArrowLeft size={14}/> Back</button>
  <Card className="p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg" style={{background:`${meta.color}1f`}}><Icon size={16} style={{color:meta.color}}/></span><span className="text-xs text-text-muted">{resource.platform||'Website'}</span><Badge tone={resource.import_status==='NEEDS_REVIEW'?'warning':'success'}>{resource.import_status}</Badge></div><h1 className="mt-4 break-words font-display text-2xl font-semibold text-text">{resource.ai_title||resource.original_url}</h1><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-text-muted">{resource.original_description||'No original description was saved.'}</p></div><button onClick={()=>toggleFavorite(resource.id)} className="shrink-0 rounded-xl border border-hairline-strong bg-elevated p-3 text-text-faint hover:text-warning" aria-label={resource.favorite?'Remove favorite':'Add favorite'}><Star size={18} className={resource.favorite?'fill-warning text-warning':''}/></button></div><div className="mt-6 flex flex-wrap gap-2">{tags.map(t=><Badge key={t} tone="neutral">{t}</Badge>)}</div><div className="mt-6 flex flex-col gap-2 sm:flex-row"><a href={resource.original_url} target="_blank" rel="noreferrer"><Button><ExternalLink size={14}/>Open original</Button></a><span className="flex min-w-0 items-center rounded-lg bg-elevated px-3 py-2 text-xs text-text-faint truncate">{resource.original_url}</span></div></Card>
  <div className="grid grid-cols-1 gap-5 lg:grid-cols-3"><div className="lg:col-span-2 space-y-5"><Card className="p-5"><div className="flex items-center gap-2"><Sparkles size={16} className="text-accent-soft"/><h2 className="text-sm font-medium text-text">AI summary</h2></div>{resource.ai_summary?<p className="mt-4 text-sm leading-6 text-text-muted">{resource.ai_summary}</p>:<div className="mt-4 rounded-lg bg-elevated p-4 text-xs text-text-faint">AI summary is not available yet. Run AI organization from your configured provider to enrich this resource.</div>}{resource.ai_use_cases?.length>0&&<div className="mt-5"><p className="text-xs font-medium text-text">Possible use cases</p><ul className="mt-2 space-y-1 text-xs text-text-muted">{resource.ai_use_cases.map(x=><li key={x}>• {x}</li>)}</ul></div>}</Card><Card className="p-5"><div className="flex items-center gap-2"><Link2 size={16} className="text-accent-soft"/><h2 className="text-sm font-medium text-text">Related resources</h2></div>{related.length?<div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-2">{related.map(r=><Link key={r.id} to={`/resource/${r.id}`} className="rounded-lg border border-hairline p-3 hover:bg-elevated"><p className="truncate text-xs font-medium text-text">{r.ai_title||r.original_url}</p><p className="mt-1 line-clamp-2 text-[11px] text-text-faint">{r.related_reason}</p></Link>)}</div>:<p className="mt-4 text-xs text-text-faint">No strong connections found yet.</p>}</Card></div><div className="space-y-5"><Card className="p-5"><h2 className="text-sm font-medium text-text">Knowledge metadata</h2><div className="mt-4 space-y-3 text-xs"><div><p className="text-text-faint">Category</p><p className="mt-1 text-text">{resource.ai_category||'Uncategorized'}</p></div><div><p className="text-text-faint">Subcategory</p><p className="mt-1 text-text">{resource.ai_subcategory||'—'}</p></div><div><p className="text-text-faint">AI status</p><p className="mt-1 flex items-center gap-1.5 text-text">{resource.ai_status==='COMPLETE'?<CheckCircle2 size={13} className="text-success"/>:<AlertCircle size={13} className="text-warning"/>}{resource.ai_status}</p></div><div><p className="text-text-faint">Saved</p><p className="mt-1 text-text">{new Date(resource.created_at).toLocaleString()}</p></div></div></Card></div></div>
 </div>
}
