import { useEffect, useState } from 'react'
import { Search as SearchIcon, X, Sparkles } from 'lucide-react'
import { api } from '../utils/api'
import { useResources } from '../context/ResourcesContext'
import ResourceCard from '../components/resources/ResourceCard'
import EmptyState from '../components/ui/EmptyState'
import ErrorState from '../components/ui/ErrorState'

const SUGGESTIONS=['Claude','Next.js','AI agent','GitHub','automation','PDF']
export default function Search(){
 const {toggleFavorite}=useResources(); const [query,setQuery]=useState(''); const [results,setResults]=useState([]); const [recent,setRecent]=useState([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{api.get('/resources/search/recent?limit=6').then(r=>setRecent(r.items||[])).catch(()=>{})},[])
 useEffect(()=>{const q=query.trim(); if(!q){setResults([]);setError('');return} const timer=setTimeout(async()=>{setLoading(true);setError('');try{const r=await api.get(`/resources/search?q=${encodeURIComponent(q)}&page_size=24`);setResults(r.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}},220);return()=>clearTimeout(timer)},[query])
 return <div className="space-y-8"><div className="mx-auto max-w-2xl pt-4 text-center"><h2 className="font-display text-2xl font-semibold text-text">Search your library</h2><p className="mt-1.5 text-[13.5px] text-text-muted">Search titles, descriptions, AI metadata, URLs and tags — locally.</p><div className="relative mt-6"><SearchIcon size={18} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-text-faint"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “AI agents” or “Next.js”…" className="h-13 w-full rounded-2xl border border-hairline-strong bg-surface pl-12 pr-11 text-[15px] text-text placeholder:text-text-faint outline-none transition-colors focus:border-accent"/>{query&&<button onClick={()=>setQuery('')} className="absolute right-4 top-1/2 -translate-y-1/2 text-text-faint hover:text-text" aria-label="Clear search"><X size={16}/></button>}</div>{!query&&<div className="mt-4 flex flex-wrap items-center justify-center gap-2"><span className="flex items-center gap-1 text-[12px] text-text-faint"><Sparkles size={12}/> Try:</span>{SUGGESTIONS.map(s=><button key={s} onClick={()=>setQuery(s)} className="rounded-full border border-hairline-strong bg-elevated px-3 py-1 text-[12.5px] text-text-muted hover:border-accent/40 hover:text-accent-soft">{s}</button>)}</div>}{!query&&recent.length>0&&<div className="mt-5 flex flex-wrap justify-center gap-2">{recent.map(q=><button key={q} onClick={()=>setQuery(q)} className="text-xs text-text-faint hover:text-text">Recent: {q}</button>)}</div>}</div>
 {error?<ErrorState description={error}/>:query&&loading?<div className="py-12 text-center text-sm text-text-muted">Searching…</div>:query&&results.length===0?<EmptyState icon={SearchIcon} title="No matches" description="Try a broader phrase, platform name, or tag."/>:query?<><div className="flex items-center justify-between"><p className="text-sm text-text-muted">{results.length} matching resources</p><span className="text-xs text-text-faint">SQLite FTS</span></div><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3">{results.map(r=><ResourceCard key={r.id} resource={{...r,title:r.ai_title||r.original_url,originalUrl:r.original_url,originalDescription:r.original_description||r.ai_summary||'',tags:r.ai_tags||[],status:r.import_status?.toLowerCase(),savedAt:r.created_at}} onToggleFavorite={toggleFavorite}/>)}</div></>:null}</div>
}
